### ISSUE TITLE
Unable to delete (The operation is unsupported.)

### ISSUE THREAD

**Issue by tylermichael** [mkuchin/docker-registry-web#35]
When I go to delete a tag by pressing "Delete", all it does is refresh the page. It never actually deletes it. In the gist, I have logs of the event.

https://gist.github.com/tylermichael/02942a986d2007a083b72e59f2edf305

**Comment by tasmar** [comment]
I am having the same issue.

**Comment by joshrivers** [comment]
I believe you have to run registry with -e REGISTRY_STORAGE_DELETE_ENABLED=true

**Comment by tasmar** [comment]
That fixed it @joshrivers thanks!

**Comment by tylermichael** [comment]
Yup, that fixed it. Thanks @joshrivers!

**Comment by LoLei** [comment]
Sorry for necrobumping this, but I ran into the same issue and the proposed solution in the [Docker documentation](https://docs.docker.com/registry/configuration/#delete) did not work, @joshrivers's solution did however. This might be due to the fact that I'm using a slightly older Docker version though.
